title: "Come usare l'intelligenza artificiale 
ed essere felici"
description: "Raccolta di materiali ( principalmente per lezioni di informatica) prodotti con l'uso dell'intelligenza artificiale"
theme: minima
